Deserialize DataSerializables
BlockJamMC/BlockJamCore pull request #4
Opened 2016-09-22 19:27 UTC by randombyte-developer

DataSerializables can now be deserialized from the config.

Example:
``` java
List<ItemStack> itemStacks = DataSerializableHelper
                            .deserializeListNode(ItemStack.class, config().getNode(ConfigKeys.QUICK_START_ITEMS));
```

2016-09-22 19:32 UTC, jamierocks commented on src/main/java/org/blockjam/core/config/ConfigManager.java
> +import static com.google.common.base.Preconditions.checkNotNull;
Please move this back.

2016-09-22 19:33 UTC, jamierocks commented on src/main/java/org/blockjam/core/config/DataSerializableHelper.java
> +/*
Wrong copyright header. Run `gradle licenseFormat`

2016-09-22 19:33 UTC, jamierocks commented on src/main/java/org/blockjam/core/config/DataSerializableHelper.java
> +     * Deserializes a {@link ConfigurationNode} to a {@link DataSerializable}.
Add a newline after this line.

2016-09-22 19:33 UTC, jamierocks commented on src/main/java/org/blockjam/core/config/DataSerializableHelper.java
> +     * Deserializes the children of a {@link ConfigurationNode} to a List of {@link DataSerializable}.
Add a newline after this line.

2016-09-22 19:34 UTC, jamierocks commented on src/main/java/org/blockjam/core/config/DataSerializableHelper.java
> +public class DataSerializableHelper {
Make the class final.

2016-09-22 19:34 UTC, jamierocks commented on src/main/java/org/blockjam/core/config/ConfigManager.java
> +     * @return The requested node; Node#getValue() may return null if a value is not set
Finish up the javadoc.

2016-09-22 19:34 UTC, jamierocks commented on src/main/java/org/blockjam/core/config/ConfigManager.java
> +     * @return The requested node; Node#getValue() is definitely non-null
Finish up the javadoc.

2016-09-22 19:34 UTC, jamierocks commented on src/main/java/org/blockjam/core/config/ConfigManager.java
> +     * @return The config value
Finish up the javadoc.

2016-09-22 19:35 UTC, jamierocks requested changes
Looking good ;)

2016-09-24 20:19 UTC, randombyte-developer commented on src/main/java/org/blockjam/core/config/ConfigManager.java
> +import static com.google.common.base.Preconditions.checkNotNull;
The IntelliJ Code Style by Google orders all static imports to bottom of the import section.

2016-09-24 21:41 UTC, caseif commented on src/main/java/org/blockjam/core/config/ConfigManager.java
> +import static com.google.common.base.Preconditions.checkNotNull;
Odd, not sure what that's about - the written specifications states that static imports precede non-static ones. We're also not strictly following Google style - we're following a derivative of it.

2016-09-24 21:43 UTC, caseif commented
LGTM after the import order change is made.

2016-09-24 21:43 UTC, randombyte-developer commented on src/main/java/org/blockjam/core/config/ConfigManager.java
> +import static com.google.common.base.Preconditions.checkNotNull;
@caseif Well, then I'll change my specific IDE settings to place statics in front.

2016-09-24 22:06 UTC, caseif commented
Sorry, can you rebase this off of the latest `master` commit?

2016-09-24 22:22 UTC, merged